### ISSUE TITLE
flow.reverse.ncnn.bin not found

### ISSUE THREAD

**Issue by potatoker** [weirdseed/vits-ncnn-convert-tool#16]
INFO:root:enc_p.encoder.attn_layers.0.attention.emb_rel_k is not in the checkpoint
INFO:root:enc_p.encoder.attn_layers.0.attention.emb_rel_v is not in the checkpoint
INFO:root:enc_p.encoder.attn_layers.1.attention.emb_rel_k is not in the checkpoint
INFO:root:enc_p.encoder.attn_layers.1.attention.emb_rel_v is not in the checkpoint
INFO:root:enc_p.encoder.attn_layers.2.attention.emb_rel_k is not in the checkpoint
INFO:root:enc_p.encoder.attn_layers.2.attention.emb_rel_v is not in the checkpoint
INFO:root:enc_p.encoder.attn_layers.3.attention.emb_rel_k is not in the checkpoint
INFO:root:enc_p.encoder.attn_layers.3.attention.emb_rel_v is not in the checkpoint
INFO:root:enc_p.encoder.attn_layers.4.attention.emb_rel_k is not in the checkpoint
INFO:root:enc_p.encoder.attn_layers.4.attention.emb_rel_v is not in the checkpoint
INFO:root:enc_p.encoder.attn_layers.5.attention.emb_rel_k is not in the checkpoint
INFO:root:enc_p.encoder.attn_layers.5.attention.emb_rel_v is not in the checkpoint
INFO:root:dec.ups.0.weight is not in the checkpoint
INFO:root:dec.ups.1.weight is not in the checkpoint
INFO:root:dec.ups.2.weight is not in the checkpoint
INFO:root:dec.ups.3.weight is not in the checkpoint
INFO:root:dec.resblocks.0.convs1.0.weight is not in the checkpoint
INFO:root:dec.resblocks.0.convs1.1.weight is not in the checkpoint
INFO:root:dec.resblocks.0.convs1.2.weight is not in the checkpoint
INFO:root:dec.resblocks.0.convs2.0.weight is not in the checkpoint
INFO:root:dec.resblocks.0.convs2.1.weight is not in the checkpoint
INFO:root:dec.resblocks.0.convs2.2.weight is not in the checkpoint
INFO:root:dec.resblocks.1.convs1.0.weight is not in the checkpoint
INFO:root:dec.resblocks.1.convs1.1.weight is not in the checkpoint
INFO:root:dec.resblocks.1.convs1.2.weight is not in the checkpoint
INFO:root:dec.resblocks.1.convs2.0.weight is not in the checkpoint
INFO:root:dec.resblocks.1.convs2.1.weight is not in the checkpoint
INFO:root:dec.resblocks.1.convs2.2.weight is not in the checkpoint
INFO:root:dec.resblocks.2.convs1.0.weight is not in the checkpoint
INFO:root:dec.resblocks.2.convs1.1.weight is not in the checkpoint
INFO:root:dec.resblocks.2.convs1.2.weight is not in the checkpoint
INFO:root:dec.resblocks.2.convs2.0.weight is not in the checkpoint
INFO:root:dec.resblocks.2.convs2.1.weight is not in the checkpoint
INFO:root:dec.resblocks.2.convs2.2.weight is not in the checkpoint
INFO:root:dec.resblocks.3.convs1.0.weight is not in the checkpoint
INFO:root:dec.resblocks.3.convs1.1.weight is not in the checkpoint
INFO:root:dec.resblocks.3.convs1.2.weight is not in the checkpoint
INFO:root:dec.resblocks.3.convs2.0.weight is not in the checkpoint
INFO:root:dec.resblocks.3.convs2.1.weight is not in the checkpoint
INFO:root:dec.resblocks.3.convs2.2.weight is not in the checkpoint
INFO:root:dec.resblocks.4.convs1.0.weight is not in the checkpoint
INFO:root:dec.resblocks.4.convs1.1.weight is not in the checkpoint
INFO:root:dec.resblocks.4.convs1.2.weight is not in the checkpoint
INFO:root:dec.resblocks.4.convs2.0.weight is not in the checkpoint
INFO:root:dec.resblocks.4.convs2.1.weight is not in the checkpoint
INFO:root:dec.resblocks.4.convs2.2.weight is not in the checkpoint
INFO:root:dec.resblocks.5.convs1.0.weight is not in the checkpoint
INFO:root:dec.resblocks.5.convs1.1.weight is not in the checkpoint
INFO:root:dec.resblocks.5.convs1.2.weight is not in the checkpoint
INFO:root:dec.resblocks.5.convs2.0.weight is not in the checkpoint
INFO:root:dec.resblocks.5.convs2.1.weight is not in the checkpoint
INFO:root:dec.resblocks.5.convs2.2.weight is not in the checkpoint
INFO:root:dec.resblocks.6.convs1.0.weight is not in the checkpoint
INFO:root:dec.resblocks.6.convs1.1.weight is not in the checkpoint
INFO:root:dec.resblocks.6.convs1.2.weight is not in the checkpoint
INFO:root:dec.resblocks.6.convs2.0.weight is not in the checkpoint
INFO:root:dec.resblocks.6.convs2.1.weight is not in the checkpoint
INFO:root:dec.resblocks.6.convs2.2.weight is not in the checkpoint
INFO:root:dec.resblocks.7.convs1.0.weight is not in the checkpoint
INFO:root:dec.resblocks.7.convs1.1.weight is not in the checkpoint
INFO:root:dec.resblocks.7.convs1.2.weight is not in the checkpoint
INFO:root:dec.resblocks.7.convs2.0.weight is not in the checkpoint
INFO:root:dec.resblocks.7.convs2.1.weight is not in the checkpoint
INFO:root:dec.resblocks.7.convs2.2.weight is not in the checkpoint
INFO:root:dec.resblocks.8.convs1.0.weight is not in the checkpoint
INFO:root:dec.resblocks.8.convs1.1.weight is not in the checkpoint
INFO:root:dec.resblocks.8.convs1.2.weight is not in the checkpoint
INFO:root:dec.resblocks.8.convs2.0.weight is not in the checkpoint
INFO:root:dec.resblocks.8.convs2.1.weight is not in the checkpoint
INFO:root:dec.resblocks.8.convs2.2.weight is not in the checkpoint
INFO:root:dec.resblocks.9.convs1.0.weight is not in the checkpoint
INFO:root:dec.resblocks.9.convs1.1.weight is not in the checkpoint
INFO:root:dec.resblocks.9.convs1.2.weight is not in the checkpoint
INFO:root:dec.resblocks.9.convs2.0.weight is not in the checkpoint
INFO:root:dec.resblocks.9.convs2.1.weight is not in the checkpoint
INFO:root:dec.resblocks.9.convs2.2.weight is not in the checkpoint
INFO:root:dec.resblocks.10.convs1.0.weight is not in the checkpoint
INFO:root:dec.resblocks.10.convs1.1.weight is not in the checkpoint
INFO:root:dec.resblocks.10.convs1.2.weight is not in the checkpoint
INFO:root:dec.resblocks.10.convs2.0.weight is not in the checkpoint
INFO:root:dec.resblocks.10.convs2.1.weight is not in the checkpoint
INFO:root:dec.resblocks.10.convs2.2.weight is not in the checkpoint
INFO:root:dec.resblocks.11.convs1.0.weight is not in the checkpoint
INFO:root:dec.resblocks.11.convs1.1.weight is not in the checkpoint
INFO:root:dec.resblocks.11.convs1.2.weight is not in the checkpoint
INFO:root:dec.resblocks.11.convs2.0.weight is not in the checkpoint
INFO:root:dec.resblocks.11.convs2.1.weight is not in the checkpoint
INFO:root:dec.resblocks.11.convs2.2.weight is not in the checkpoint
INFO:root:flow.flows.0.enc.in_layers.0.weight is not in the checkpoint
INFO:root:flow.flows.0.enc.in_layers.1.weight is not in the checkpoint
INFO:root:flow.flows.0.enc.in_layers.2.weight is not in the checkpoint
INFO:root:flow.flows.0.enc.in_layers.3.weight is not in the checkpoint
INFO:root:flow.flows.0.enc.res_skip_layers.0.weight is not in the checkpoint
INFO:root:flow.flows.0.enc.res_skip_layers.1.weight is not in the checkpoint
INFO:root:flow.flows.0.enc.res_skip_layers.2.weight is not in the checkpoint
INFO:root:flow.flows.0.enc.res_skip_layers.3.weight is not in the checkpoint
INFO:root:flow.flows.0.enc.cond_layer.weight is not in the checkpoint
INFO:root:flow.flows.2.enc.in_layers.0.weight is not in the checkpoint
INFO:root:flow.flows.2.enc.in_layers.1.weight is not in the checkpoint
INFO:root:flow.flows.2.enc.in_layers.2.weight is not in the checkpoint
INFO:root:flow.flows.2.enc.in_layers.3.weight is not in the checkpoint
INFO:root:flow.flows.2.enc.res_skip_layers.0.weight is not in the checkpoint
INFO:root:flow.flows.2.enc.res_skip_layers.1.weight is not in the checkpoint
INFO:root:flow.flows.2.enc.res_skip_layers.2.weight is not in the checkpoint
INFO:root:flow.flows.2.enc.res_skip_layers.3.weight is not in the checkpoint
INFO:root:flow.flows.2.enc.cond_layer.weight is not in the checkpoint
INFO:root:flow.flows.4.enc.in_layers.0.weight is not in the checkpoint
INFO:root:flow.flows.4.enc.in_layers.1.weight is not in the checkpoint
INFO:root:flow.flows.4.enc.in_layers.2.weight is not in the checkpoint
INFO:root:flow.flows.4.enc.in_layers.3.weight is not in the checkpoint
INFO:root:flow.flows.4.enc.res_skip_layers.0.weight is not in the checkpoint
INFO:root:flow.flows.4.enc.res_skip_layers.1.weight is not in the checkpoint
INFO:root:flow.flows.4.enc.res_skip_layers.2.weight is not in the checkpoint
INFO:root:flow.flows.4.enc.res_skip_layers.3.weight is not in the checkpoint
INFO:root:flow.flows.4.enc.cond_layer.weight is not in the checkpoint
INFO:root:flow.flows.6.enc.in_layers.0.weight is not in the checkpoint
INFO:root:flow.flows.6.enc.in_layers.1.weight is not in the checkpoint
INFO:root:flow.flows.6.enc.in_layers.2.weight is not in the checkpoint
INFO:root:flow.flows.6.enc.in_layers.3.weight is not in the checkpoint
INFO:root:flow.flows.6.enc.res_skip_layers.0.weight is not in the checkpoint
INFO:root:flow.flows.6.enc.res_skip_layers.1.weight is not in the checkpoint
INFO:root:flow.flows.6.enc.res_skip_layers.2.weight is not in the checkpoint
INFO:root:flow.flows.6.enc.res_skip_layers.3.weight is not in the checkpoint
INFO:root:flow.flows.6.enc.cond_layer.weight is not in the checkpoint
INFO:root:enc_q.enc.in_layers.0.weight is not in the checkpoint
INFO:root:enc_q.enc.in_layers.1.weight is not in the checkpoint
INFO:root:enc_q.enc.in_layers.2.weight is not in the checkpoint
INFO:root:enc_q.enc.in_layers.3.weight is not in the checkpoint
INFO:root:enc_q.enc.in_layers.4.weight is not in the checkpoint
INFO:root:enc_q.enc.in_layers.5.weight is not in the checkpoint
INFO:root:enc_q.enc.in_layers.6.weight is not in the checkpoint
INFO:root:enc_q.enc.in_layers.7.weight is not in the checkpoint
INFO:root:enc_q.enc.in_layers.8.weight is not in the checkpoint
INFO:root:enc_q.enc.in_layers.9.weight is not in the checkpoint
INFO:root:enc_q.enc.in_layers.10.weight is not in the checkpoint
INFO:root:enc_q.enc.in_layers.11.weight is not in the checkpoint
INFO:root:enc_q.enc.in_layers.12.weight is not in the checkpoint
INFO:root:enc_q.enc.in_layers.13.weight is not in the checkpoint
INFO:root:enc_q.enc.in_layers.14.weight is not in the checkpoint
INFO:root:enc_q.enc.in_layers.15.weight is not in the checkpoint
INFO:root:enc_q.enc.res_skip_layers.0.weight is not in the checkpoint
INFO:root:enc_q.enc.res_skip_layers.1.weight is not in the checkpoint
INFO:root:enc_q.enc.res_skip_layers.2.weight is not in the checkpoint
INFO:root:enc_q.enc.res_skip_layers.3.weight is not in the checkpoint
INFO:root:enc_q.enc.res_skip_layers.4.weight is not in the checkpoint
INFO:root:enc_q.enc.res_skip_layers.5.weight is not in the checkpoint
INFO:root:enc_q.enc.res_skip_layers.6.weight is not in the checkpoint
INFO:root:enc_q.enc.res_skip_layers.7.weight is not in the checkpoint
INFO:root:enc_q.enc.res_skip_layers.8.weight is not in the checkpoint
INFO:root:enc_q.enc.res_skip_layers.9.weight is not in the checkpoint
INFO:root:enc_q.enc.res_skip_layers.10.weight is not in the checkpoint
INFO:root:enc_q.enc.res_skip_layers.11.weight is not in the checkpoint
INFO:root:enc_q.enc.res_skip_layers.12.weight is not in the checkpoint
INFO:root:enc_q.enc.res_skip_layers.13.weight is not in the checkpoint
INFO:root:enc_q.enc.res_skip_layers.14.weight is not in the checkpoint
INFO:root:enc_q.enc.res_skip_layers.15.weight is not in the checkpoint
INFO:root:enc_q.enc.cond_layer.weight is not in the checkpoint
INFO:root:Loaded checkpoint '/apdcephfs/share_1227775/raymondguo/tools/alice/alice.pth' (iteration 1143)
sh: pnnx/pnnx: Permission denied
sh: pnnx/pnnx: Permission denied
/apdcephfs/share_1227775/raymondguo/tools/vits-ncnn-convert-tool/attentions.py:133: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert t_s == t_t, "Relative attention is only available for self-attention."
/apdcephfs/share_1227775/raymondguo/tools/vits-ncnn-convert-tool/attentions.py:181: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  pad_length = max(length - (self.window_size + 1), 0)
/apdcephfs/share_1227775/raymondguo/tools/vits-ncnn-convert-tool/attentions.py:182: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  slice_start_position = max((self.window_size + 1) - length, 0)
/apdcephfs/share_1227775/raymondguo/tools/vits-ncnn-convert-tool/attentions.py:184: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if pad_length > 0:
sh: pnnx/pnnx: Permission denied
sh: pnnx/pnnx: Permission denied
sh: pnnx/pnnx: Permission denied
/root/miniconda3/envs/vits-ncnn/lib/python3.10/site-packages/torch/jit/_trace.py:1001: TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:
Tensor-likes are not close!

Mismatched elements: 64506 / 64512 (100.0%)
Greatest absolute difference: 0.5184453725814819 at index (0, 42, 294) (up to 1e-05 allowed)
Greatest relative difference: 1387.0333428734975 at index (0, 105, 80) (up to 1e-05 allowed)
  _check_trace(
sh: pnnx/pnnx: Permission denied
Traceback (most recent call last):
  File "/tools/vits-ncnn-convert-tool/convert_model.py", line 224, in <module>
    main(args)
  File "/tools/vits-ncnn-convert-tool/convert_model.py", line 198, in main
    export(cache_root, out_root, name)
  File "/tools/vits-ncnn-convert-tool/convert_model.py", line 98, in export
    shutil.copy(src_path, target_path)
  File "/root/miniconda3/envs/vits-ncnn/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/root/miniconda3/envs/vits-ncnn/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'ncnn_cache/flow_reverse/flow.reverse.ncnn.bin'

I'm using pretrained model from https://huggingface.co/spaces/zomehwh/vits-models-genshin-bh3/tree/main/pretrained_models/alice 

have no idea what is happening

**Comment by potatoker** [comment]
the main problem is "pnnx/pnnx: Permission denied", after change the priority of the pnnx directory , this error is gone
