### ISSUE TITLE
This cleaner is not supported

### ISSUE THREAD

**Issue by onexuan** [weirdseed/vits-ncnn-convert-tool#2]
Traceback (most recent call last):
  File "/Users/xxx/Downloads/vits-ncnn-convert-tool-1.1/convert_model.py", line 221, in <module>
    main(args)
  File "/Users/xxx/Downloads/vits-ncnn-convert-tool-1.1/convert_model.py", line 136, in main
    raise RuntimeError("This cleaner is not supported!")

**Comment by weirdseed** [comment]
由于App只支持"japanese_cleaners","japanese_cleaners2","chinese_cleaners"这三个cleaner，所以我加了限制，如果单纯转换模型建议把相关代码删掉比如说[134行](https://github.com/weirdseed/vits-ncnn-convert-tool/blob/master/convert_model.py#L134)到[136行](https://github.com/weirdseed/vits-ncnn-convert-tool/blob/master/convert_model.py#L136)

**Comment by onexuan** [comment]
那请问现在哪个模型支持APP转音频，想试试看

**Comment by weirdseed** [comment]
https://github.com/CjangCjengh/TTSModels 这个页面的Japanese模型都支持，支不支持主要看JSON文件的cleaner

**Comment by onexuan** [comment]
> 那请问现在哪个模型支持APP转音频，想试试看

打错了，是“那请问现在哪个模型支持APP转中文音频，想试试看，你打包的model，只支持日语？”

**Comment by weirdseed** [comment]
> 

可以参考这个项目https://github.com/rotten-work/vits-mandarin-windows
