### ISSUE TITLE
我是Mac環境使用python，轉換失敗（模型是下載的）

### ISSUE THREAD

**Issue by a9460620** [weirdseed/vits-ncnn-convert-tool#9]
不好意思，像這種模型能不能轉換，我是用bronya的

https://huggingface.co/spaces/zomehwh/vits-models/tree/main/pretrained_models

Tensor-likes are not close!

Mismatched elements: 64509 / 64512 (100.0%)
Greatest absolute difference: 0.5846505761146545 at index (0, 42, 157) (up to 1e-05 allowed)
Greatest relative difference: 46054.02290076336 at index (0, 105, 59) (up to 1e-05 allowed)
  _check_trace(
sh: pnnx/pnnx: cannot execute binary file
Traceback (most recent call last):
  File "/Users/liangboyao/Downloads/vits-ncnn-convert-tool-1.1/convert_model.py", line 221, in <module>
    main(args)
  File "/Users/liangboyao/Downloads/vits-ncnn-convert-tool-1.1/convert_model.py", line 195, in main
    export(cache_root, out_root, name)
  File "/Users/liangboyao/Downloads/vits-ncnn-convert-tool-1.1/convert_model.py", line 97, in export
    shutil.copy(src_path, target_path)
  File "/Users/liangboyao/anaconda3/envs/vits-ncnn/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/liangboyao/anaconda3/envs/vits-ncnn/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'ncnn_cache/flow_reverse/flow.reverse.ncnn.bin'

**Comment by weirdseed** [comment]
请到这里下载macos版[pnnx](https://github.com/pnnx/pnnx/releases)
